In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [5]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [6]:
df['brand'].nunique() # we have 32 different brands

32

## 1. OneHotEncoding using pandas

In [7]:
pd.get_dummies(df, columns=['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

## K-1 OneHotEncoding
#### Remove Multicollinearity

In [8]:
pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## OneHotEncoding using Sci-kit learn

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=None)

In [10]:
X_train.head()

        brand  km_driven    fuel         owner
3669   Toyota     160000  Diesel   First Owner
4733   Datsun      31100  Petrol   First Owner
5564     Tata      90000  Diesel  Second Owner
3106  Hyundai      39000  Petrol   First Owner
1242  Hyundai      15000  Petrol   First Owner

In [11]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first')

In [12]:
X_train_new = encoder.fit_transform(X_train[['fuel', 'owner']]).toarray()

In [13]:
X_train_new.shape

(6502, 7)

In [14]:
X_test_new = encoder.fit_transform(X_test[['fuel', 'owner']]).toarray()

In [15]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new)).shape

(6502, 9)

In [16]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Toyota', 160000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Datsun', 31100, 0.0, ..., 0.0, 0.0, 0.0],
       ['Tata', 90000, 1.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Mahindra', 115717, 1.0, ..., 0.0, 0.0, 0.0],
       ['Mahindra', 70000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Chevrolet', 70000, 0.0, ..., 1.0, 0.0, 0.0]],
      shape=(6502, 9), dtype=object)

In [17]:
np.hstack((X_test[['brand', 'km_driven']].values, X_test_new))

array([['Toyota', 150000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Chevrolet', 68000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 55000, 0.0, ..., 1.0, 0.0, 0.0],
       ...,
       ['Mahindra', 74000, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 38600, 1.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 56290, 1.0, ..., 0.0, 0.0, 0.0]],
      shape=(1626, 9), dtype=object)

## OneHotEncoding with Top Categories

In [32]:
counts = df['brand'].value_counts()

In [33]:
counts

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [34]:
df['brand'].nunique()

32

In [35]:
# let's take a threshold of 100 cars that will be the minimum limit to have a column of a car brand
threshold = 100

In [37]:
replace_column = counts[counts <= threshold].index

In [38]:
replace_column

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Land', 'Force', 'Isuzu', 'Ambassador',
       'Kia', 'MG', 'Daewoo', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [41]:
new_df = pd.get_dummies(df['brand'].replace(replace_column, 'others'))

In [43]:
new_df.sample(20)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,others
7722,False,False,False,False,False,False,False,False,False,True,False,False,False
1350,False,False,False,False,False,False,True,False,False,False,False,False,False
4102,False,False,False,True,False,False,False,False,False,False,False,False,False
7119,False,False,False,False,False,False,False,False,False,False,False,False,True
2540,False,True,False,False,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,False,False,False,True
376,False,False,False,False,False,False,True,False,False,False,False,False,False
5771,False,False,False,False,True,False,False,False,False,False,False,False,False
6800,False,False,False,False,False,True,False,False,False,False,False,False,False
5122,False,False,False,False,False,True,False,False,False,False,False,False,False
7465,False,False,True,False,False,False,False,False,False,False,False,False,False
4427,False,False,False,False,True,False,False,False,False,False,False,False,False
171,False,False,False,False,False,False,False,False,False,False,False,True,False
6101,False,False,False,False,False,False,True,False,False,False,False,False,False
4561,False,False,False,True,False,False,False,False,False,False,False,False,False
2452,False,False,False,False,False,False,False,False,False,True,False,False,False
1590,False,False,False,False,False,False,False,False,False,True,False,False,False
5100,False,False,False,False,False,False,False,False,True,False,False,False,False
5432,False,False,False,False,True,False,False,False,False,False,False,False,False
7630,False,False,False,False,False,False,False,False,False,False,True,False,False