In [41]:
import numpy as np
import pandas as pd

In [42]:
df = pd.read_csv('synthetic_nominal_customer.csv')

In [43]:
df.sample(5)

     age    country device_type payment_method purchase_complete
406   52    Germany      tablet           cash                no
886   64  Australia      mobile       ibanking                no
670   34    Germany      mobile           card               yes
190   52         UK      mobile           cash                no
761   25    Germany      mobile         wallet               yes

### pandas OneHotEncoding

In [44]:
pandas_one_hot_encoding = pd.get_dummies(df, columns=['country', 'device_type', 'payment_method'], prefix=None, prefix_sep='_', dummy_na=False, sparse=False, drop_first=True, dtype=None)

In [45]:
pandas_one_hot_encoding

,age,purchase_complete,country_Germany,country_UK,country_USA,device_type_mobile,device_type_tablet,payment_method_cash,payment_method_ibanking,payment_method_wallet
0,27,no,False,False,True,True,False,True,False,False
1,19,no,False,False,False,True,False,False,False,True
2,47,yes,False,True,False,True,False,False,False,False
3,50,no,False,False,True,True,False,True,False,False
4,54,yes,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
995,27,yes,False,False,False,False,False,False,False,False
996,58,yes,False,False,True,True,False,False,True,False
997,64,yes,True,False,False,True,False,False,False,True
998,53,yes,False,True,False,False,False,False,True,False
999,22,yes,True,False,False,True,False,True,False,False

## Sci-kit learn OneHotEncoding

### Train-test splip
#### (It is a good practice to split the training and testing data)

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:4], df.iloc[:,-1], test_size=0.2, random_state=None)

In [48]:
X_train

       country device_type payment_method
943  Australia      mobile         wallet
536  Australia     desktop           card
561    Germany     desktop           cash
116        USA      mobile           card
993    Germany      mobile       ibanking
..         ...         ...            ...
559  Australia     desktop       ibanking
756    Germany      mobile       ibanking
190         UK      mobile           cash
593  Australia      mobile       ibanking
699    Germany     desktop           card

[800 rows x 3 columns]

In [49]:
y_train

943     no
536    yes
561    yes
116    yes
993    yes
      ...
559    yes
756    yes
190     no
593    yes
699    yes
Name: purchase_complete, Length: 800, dtype: object

In [52]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

In [65]:
X_train_transformed = encoder.fit_transform(X_train).toarray()