In [26]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv('synthetic_nominal_customer.csv')

In [28]:
df.sample(5)

     age    country device_type payment_method purchase_complete
408   44    Germany     desktop           cash               yes
839   51  Australia     desktop         wallet               yes
264   57         UK      mobile       ibanking               yes
531   62        USA      mobile           card               yes
780   27    Germany      mobile         wallet               yes

### pandas OneHotEncoding

In [29]:
pandas_one_hot_encoding = pd.get_dummies(df, columns=['country', 'device_type', 'payment_method'], prefix=None, prefix_sep='_', dummy_na=False, sparse=False, drop_first=True, dtype=None)

In [30]:
pandas_one_hot_encoding

,age,purchase_complete,country_Germany,country_UK,country_USA,device_type_mobile,device_type_tablet,payment_method_cash,payment_method_ibanking,payment_method_wallet
0,27,no,False,False,True,True,False,True,False,False
1,19,no,False,False,False,True,False,False,False,True
2,47,yes,False,True,False,True,False,False,False,False
3,50,no,False,False,True,True,False,True,False,False
4,54,yes,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...
995,27,yes,False,False,False,False,False,False,False,False
996,58,yes,False,False,True,True,False,False,True,False
997,64,yes,True,False,False,True,False,False,False,True
998,53,yes,False,True,False,False,False,False,True,False
999,22,yes,True,False,False,True,False,True,False,False

## Sci-kit learn OneHotEncoding

### Train-test splip
#### (It is a good practice to split the training and testing data)

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2, random_state=None)

In [33]:
X_train

     age    country device_type payment_method
115   30         UK      mobile           cash
329   41    Germany      mobile         wallet
427   24        USA      mobile           cash
517   49        USA      tablet           card
406   52    Germany      tablet           cash
..   ...        ...         ...            ...
898   48    Germany      mobile         wallet
854   37    Germany     desktop           card
877   29    Germany      mobile           cash
21    39  Australia     desktop           card
658   42  Australia      mobile           cash

[800 rows x 4 columns]

In [34]:
y_train

115     no
329    yes
427     no
517    yes
406     no
      ...
898    yes
854     no
877     no
21      no
658     no
Name: purchase_complete, Length: 800, dtype: object

In [35]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first')

In [36]:
X_train_transformed = encoder.fit_transform(X_train[['country', 'device_type', 'payment_method']]).toarray()

In [38]:
X_train_transformed.shape

(800, 8)

In [39]:
X_test_transformed = encoder.fit_transform(X_test[['country', 'device_type', 'payment_method']]).toarray()

In [40]:
X_test_transformed.shape

(200, 8)

In [44]:
np.hstack((X_train[['country', 'device_type', 'payment_method']], X_train_transformed))

array([['UK', 'mobile', 'cash', ..., 1.0, 0.0, 0.0],
       ['Germany', 'mobile', 'wallet', ..., 0.0, 0.0, 1.0],
       ['USA', 'mobile', 'cash', ..., 1.0, 0.0, 0.0],
       ...,
       ['Germany', 'mobile', 'cash', ..., 1.0, 0.0, 0.0],
       ['Australia', 'desktop', 'card', ..., 0.0, 0.0, 0.0],
       ['Australia', 'mobile', 'cash', ..., 1.0, 0.0, 0.0]],
      shape=(800, 11), dtype=object)

In [47]:
np.hstack((X_test[['country', 'device_type', 'payment_method']], X_test_transformed))

array([['USA', 'mobile', 'card', ..., 0.0, 0.0, 0.0],
       ['Australia', 'mobile', 'card', ..., 0.0, 0.0, 0.0],
       ['USA', 'mobile', 'card', ..., 0.0, 0.0, 0.0],
       ...,
       ['Australia', 'mobile', 'cash', ..., 1.0, 0.0, 0.0],
       ['Germany', 'desktop', 'card', ..., 0.0, 0.0, 0.0],
       ['UK', 'desktop', 'wallet', ..., 0.0, 0.0, 1.0]],
      shape=(200, 11), dtype=object)

In [41]:
df['country'].value_counts()

country
Germany      361
USA          246
Australia    242
UK           151
Name: count, dtype: int64

In [42]:
df['device_type'].value_counts()

device_type
mobile     592
desktop    297
tablet     111
Name: count, dtype: int64

In [43]:
df['payment_method'].value_counts()

payment_method
cash        276
wallet      252
card        248
ibanking    224
Name: count, dtype: int64